### ISSUE TITLE
Kabel Schneiden

### ISSUE THREAD

**Issue by M4D1NG3R** [chris7topher/SmartPhilips2200#1]
Also erstmal echt cools Projekt,

ich habe mir gestern auch eine Philips EP2220/10 bestellt. Ich Wechsel von einer Smarter Coffee nun zu einem Vollautomaten, da mir der Kaffee auf der Smarter einfach nicht richtig schmeckt. Leider dauert es noch ein paar Tage bis diese geliefert wird.

Du hast in deinem 1. Video gesagt, dass du Kontakte an die Kabel gelötet hast. Ist das Kabel fest am Display verbaut oder sind dort Kontakte, sodass man evtl. durch Adapter o.Ä. auch ohne die original Kabel zu beschädigen die zusätzlichen Kabel anklemmen kann? 

Und könntest du evtl. mal ein Bild in einer etwas besseren Auflösung als in deinem Video von der Schnittstelle am Display machen, das  würde mir zusätzlich wirklich helfen.

Schonmal Danke für deine Antwort!

LG

**Comment by chris7topher** [comment]
Hallo,

das Kabel ist am Display angesteckt. Leider habe ich erst zu spät erfahren, dass es sich um einen Picoflex Stecker von Molex handelt. Schau am besten mal ins iobroker Forum, da habe ich mal ein paar Bilder eingestellt, wie ich das mittels Steckverbindungen gelöst habe:
[https://forum.iobroker.net/topic/30870/philips-kaffeevollautomat-ep2220-10-mittels-iobroker-steuern/21](forum.iobroker)

Am coolsten wäre es natürlich das einfach mit einem Picoflex Stecker als Zwischenmodul zu bauen.

**Comment by M4D1NG3R** [comment]
Vielen Dank für die schnelle Antwort. Wieviele Pole hat denn das Picoflex Kabel?
Dann würde ich mir gleich eine Verlängerung bestellen :)

**Comment by chris7topher** [comment]
Das ist ein 8 poliger Stecker. Das hier müsste der Typ vom Kabel zur Maschine hin sein: 90327-0308
Dazu bräuchtest du halt noch das männliche Gegenstück, das gibt es aber meines Wissens nach nur für Platinen zum auflöten. Beispielsweise das hier müsste laut Datenblatt passen: 90325-7008
